#!/usr/bin/env bash

# Update package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Configure nginx to listen on port 80
sudo sed -i 's/.*listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo ufw allow "Nginx HTTP"
# Restart nginx
sudo service nginx restart

# Create a custom HTML file with "Hello World!" content
echo "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

echo "Nginx installed and configured successfully."
