#!/usr/bin/env bash
# Redirect to another page
# The redirection must be a "301 Moved Permanently"

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow incoming HTTP traffic
sudo ufw allow "Nginx HTTP"

# Create a default "Hello World" page
echo "Hello World" | sudo tee /var/www/html/index.html

# Define the redirected URL
redirected_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Add a location block for redirection to Nginx configuration
sudo sed -i "/server_name _;/a
    location /redirect_me {
        return 301 $redirected_url;
    }" /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
