#!/usr/bin/env bash
# Redirect to another page the redirection must be a "301 Moved Permanently"

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create directories and files
sudo ufw allow "Nginx HTTP"
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx to Redirect to another page The redirection must be a "301 Moved Permanently"
sudo sed -i "/sever_name_;/a \\
    \tlocation /redirect_me { \\
        \t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \\
    \t}" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
