#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World" | sudo tee /var/www/html/index.html
redirected_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "/server_name _;/a \\
    \tlocation /redirect_me { \\
        \treturn 301 $redirected_url; \\
    \t}" /etc/nginx/sites-available/default
sudo service nginx start
