#!/usr/bin/env bash
#Not found page (404)

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html; \
    location /xyz.html { \
        internal; \
    }' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
