#!/usr/bin/env bash
# Configure server with HAproxy
# Distribute requests using a roundrobin algorithm

sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    daemon
    maxconn 100
defaults
    mode http
    timeout client 5000ms
    timeout connect 5000ms
    timeout server 5000ms
listen appname
    bind 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 18996-web-01 3.85.16.98:80 check
    server 18996-web-02 18.204.11.165:80 check
EOF
sudo service haproxy start
