#!/usr/bin/env bash
# allow for nginx port 80

# Start Nginx service
sudo apt update
sudo apt -y install nginx
sudo service nginx start
# Add firewall rule to allow traffic on port 80
sudo ufw allow 80

# Update Nginx configuration to listen on port 80
sudo sed -i 's/listen\s*80;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
