#!/usr/bin/env bash

# Install firewall and block all incoming traffic except 22, 443, 80 tcp ports traffic

sudo apt update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
