#!/usr/bin/env bash

# run software as another user

# Check if a username is provided as an argument
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Run the 'whoami' command as the specified user
sudo -u "$1" whoami
