#!/usr/bin/env bash
# Run nginx as nginx and not root

# Configure Nginx to run as nginx user
sudo sed -i 's/#user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx default server configuration to listen on port 8080 and all active IPs
sudo sed -i 's/listen\s*80\s*default_server;/listen 8080 default_server;/' /etc/nginx/conf.d/default.conf

# Restart Nginx service
sudo service nginx restart
