#!/usr/bin/env bash
# Run nginx as nginx and not root

sed -i 's/#user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80\s*default_server;/listen 8080 default_server;/' /etc/nginx/conf.d/default.conf
service nginx restart
